---
title: "index"
author: "CaroleS"
date: "11/30/2017"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```
## Data Wrangling with 'dplyr'
```{r}
library(tidyverse)

gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

gapminder
## useful functions to get to know your data:
head(gapminder) #show the first 6 rows of data
tail(gapminder) #sow the last 6 rows of data

head(gapminder,10)
tail(gapminder,9)
##check out the structure of your data
str(gapminder)
##column headers
names(gapminder)

dim(gapminder)
ncol(gapminder)
nrow(gapminder)
c(nrow(gapminder), ncol(gapminder))

summary(gapminder)
## for everything above, we are operating on the whole gapminder dataset
head(gapminder$lifeExp)

##Actually working with dplyr

filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
gapminder %>% head()
sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)
gapminder %>% 
   filter(country == "Sweden") %>% 
   summarize(mean_lifeExp = mean(lifeExp))
gapminder %>%
   filter(country == "Cambodia") %>%
   select(country, year, pop, gdpPercap)
gapminder %>%
  filter(country == "Mexico", year == 2002)
## 'mutate()' to add columns
gapminder %>%
  mutate(gdp = pop * gdpPercap)
# let's add an index column
gapminder %>%
  mutate(index = 1:nrow(gapminder))%>%
  tail()

#not the right way  
gapminder %>%
  filter(country == c("Egypt", "Vietnam"))

## '%in%' operator lets you filter multiple things within a 'c()' thing
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  mutate(max_gdpPercap = max(gdpPercap))

## group_by() so that we can get 2 maxes
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  group_by(country) %>%
  summarise(max_gdpPercap = max(gdpPercap))

gapminder %>%
  group_by(country) %>%
  summarise(max_gdpPercap = max(gdpPercap))

## let's keep the year associated with the max_gdpPercap
gapminder %>%
  group_by(country) %>%
  mutate(max_gdpPercap = max(gdpPercap)) %>%
  filter(max_gdpPercap == gdpPercap) 

## arrange by g
gapminder %>%
  group_by(country) %>%
  mutate(max_gdpPercap = max(gdpPercap)) %>%
  filter(max_gdpPercap == gdpPercap) %>%
  arrange(max_gdpPercap)
```
##joining datasets

```{r}
## 
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")
co2 %>% head()
co2 %>% str()
gap_2007 <- gapminder %>% 
  filter(year == 2007)
gap_2007 %>% head()
gap_2007 %>%  str()

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
lj %>% dim() #142 rows
# lj %>% View()

## right_join gap_2007 to co2
rj <- right_join(gap_2007, co2)
rj %>% dim()
# rj %>% View()

```

```{r}
library(tidyverse)
```
## Example datasets
```{r}
AirPassengers

```
```{r read_in_data}
# wide format
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')

## yesterday's format (intermediate)
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
head(gap_wide)
head(gapminder)
## 'gather()'
```
```{r}
gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         dplyr::starts_with('pop'),
         dplyr::starts_with('lifeExp'),
         dplyr::starts_with('gdpPercap'))  #here i'm listing all the columns to use in gather

str(gap_long)
head(gap_long)
tail(gap_long)

```
```{r}
gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         -continent, -country)

str(gap_long)
head(gap_long)
tail(gap_long)
```
```{r}
gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values,
         continent, -country) %>%
  separate(obstype_year,
           into = c('obs_type','year'),
           sep = "_",
           convert = T) #this ensures that the year column is an integer rather than a character
head(gap_long)
```
```{r}
life_df <- gap_long %>%
  filter(obs_type == "lifeExp",
         continent == "Americas")
head(life_df)
ggplot(life_df, aes(x = year, y = obs_values, color = country)) +
  geom_line()


gap_long %>% 
  group_by(continent obs_type) %>% 
     summarize(means = mean(obs_values))
head(gap_long)

```

```{r}
head(gap_long)
gap_normal <- gap_long %>% 
  spread(key = obs_type,
         value = obs_values)
head(gap_normal)
```
```{r}
head(gap_long) # remember the columns

gap_wide_new <- gap_long %>% 
  # first unite obs_type and year into a new column called var_names. Separate by _
  unite(col = var_names, obs_type, year, sep = "_") %>% 
  # then spread var_names out by key-value pair.
  spread(key = var_names, value = obs_values)
str(gap_wide_new)
```


```{r}

gap_long %>% 
  group_by(continent obs_type) %>% 
     summarize(means = mean(obs_values))
head(gap_long)

```



## `geom_point`

```{r scatterplot}
# data()
# ?mpg
#mpg
ggplot(data = mpg, aes(x = displ, y = hwy)) + 
  geom_point()
```

### `color`!

```{r color}
ggplot(data = mpg, aes(x = displ, y = hwy, color=class)) + 
  geom_point()
```

### `shape`: need a b&w figure

Changed `color` to `shape`:

```{r b&w}
ggplot(data = mpg, aes(x = displ, y = hwy, shape=class)) + 
  geom_point()
```

## `size`

```{r size}
#?mpg
ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color = fl)) + 
  geom_point(alpha = 0.2)
```


```{r fix color}
#?mpg
ggplot(data = mpg, aes(x = cty, y = hwy, size = class)) + 
  geom_point(alpha = 0.2, color = "blue")
```

## Exercise

```{r exercise 1}

ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy), color = "blue")

ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy, color = displ < 5))
```

## Geoms

```{r geom_examples}

ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_violin()

```

## Multiple geoms

```{r mult_geoms}

ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy)) +
  geom_smooth(aes(x = displ, y = hwy))

?geom_smooth

ggplot(data = mpg, aes(x = displ, y = hwy))+
  geom_point() +
  geom_smooth()
```

## Customization

```{r customize}

ggplot(data = mpg, aes(x = displ, y = hwy))+
  geom_point() +
  geom_smooth() +
  labs(title = "Relationship b/w engine size & MPG",
       x = "Highway MPG",
       y = "Engine displacement (liters)") +
  theme_bw() +
  theme(text = element_text(size = 16))

```




## Boxplot
